SAMPLE_TIME_S = 0.001
CUTOFF_FREQUENCY_HZ = 250
CUTOFF_FREQUENCY2_HZ = 350
NUM_TOTAL_SAMPLES = 64
NUM_SHIFT_SAMPLES = 32
Window_type = 9
Filter_type = 4
NUM_FREQ_SAMPLES = 10000
# print(ComputeResponse(NUM_TOTAL_SAMPLES,CUTOFF_FREQUENCY_HZ,CUTOFF_FREQUENCY2_HZ,SAMPLE_TIME_S,NUM_SHIFT_SAMPLES,3))
# print(time_vector(NUM_TOTAL_SAMPLES,SAMPLE_TIME_S))
# a = []
